mavlink/mavlink-camera-manager

- src/video/types.rs
- src/video/video_source_local.rs
This commit prevents duplicated sizes and intervals (as reported on #12) from being accepted on video data structures.
Should fix #12.
---
I don't know enough of Rust yet to say if this approach is good, but I can say it works. Anyway, let me know how we can improve it =)
> src: video: prevent size and interval duplicates

- build.rs
This commit fixes the warning: "use of deprecated function `vergen::gen`:
Please use the `vergen` function instead"
> build: fix deprecated function vergen::gen warning

- src/settings/manager.rs
- src/video/video_source_local.rs
Because usb descriptions can be way more complex than was expected, we are changing it to be the entire string instead of trying to interpret its parts to populate fields of a struct.
Fix #20.
> Use string for usb device description.

- Cargo.lock
- Cargo.toml
v4l v0.12.0 -> v0.12.1
serde v^1.0.8 -> v1.0.133
rand v0.8 -> v0.8.4
directories v3.0.1 -> v4.0.1
vergen v4 -> v6.0.0
quick-xml v0.21 -> v0.22.0
gstreamer v0.18.0 -> v0.18.1
simple-error v0.2 -> v0.2.3
url v2 -> v2.2.2
mavlink v0.8.6 -> v0.10.0
log v0.4 -> v0.4.14
sys-info v0.8.0 -> v0.9.1
reqwest v0.11 -> v0.11.9
pnet v0.27.2 -> v0.29.0
serde_derive v^1.0.8 -> v1.0.133
serde_json v^1.0.41 -> v1.0.75
regex v1.3 -> v1.5.4
glib v0.15.0 -> v0.15.2
env_logger v0.8.3 -> v0.9.0
actix-web v3.3.2 -> v3.3.3
> Upgrade several dependencies

- src/html/index.html
> src: html: Use a default endpoint when not set.

- src/mavlink/mavlink_camera.rs
Should fix #33
The function that does the was getting `"9963776\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"` in the `param_id` when changing the _Brightness_ control on QGC, and the code is trying to parse this entire string as a `u64`, which fails.
One quick solution is to remove the trailing \0 before the parsing, as shown in [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1ff202343838bd5d4dd01a03cf1e8ab3).
> src: mavlink: Remove trailing null bytes before parsing the control id.

- src/html/index.html
Fix #48.
Details:
We were accessing the "extended_configuration" filed without checking its existence, which will cause invalid access in the case of loading an older configuration.
I couldn't get rid of the uncoherent "null" from being shown on the stream description, but at least it is loading normally with this patch, considering thermal as "false" when "extended_configuration" is "null".
> src: html: Make the frontend tolerate null extended_configuration.

- src/video/video_source.rs
- src/video/video_source_gst.rs
- src/video/video_source_local.rs
- src/video/video_source_redirect.rs
- src/video_stream/types.rs
This enables both Redirect and Gst video sources to be shared by multiple streams.
> Shared video sources

- src/video/video_source_local.rs
The following errors are caused by this unwanted access to CtrlClass:
> Fix unwanted access to CtrlClass

- .gitignore
Necessary since the files are downloaded during our build step
> gitignore: Add webrtc html adapter

- src/video/types.rs
- src/video/video_source_local.rs
This PR is one step further to #66. Actually, with this implementation, the raspberry pi camera works in legacy mode, but more test is needed.
> Add stepwise support

- Cargo.lock
- Cargo.toml
fixes: https://github.com/joaoantoniocardoso/mavlink-camera-manager/security/dependabot/2
> Cargo: Update tokio to 1.19, fixing vulnerability.

- src/stream/gst/pipeline_builder.rs
- src/stream/stream_backend.rs
- src/video/video_source_local.rs
Closes #66.
Finally, with this PR, Raspberry Pi Camera will be working, but with the following notes:
- Only Legacy Camera mode is supported, to do so, one needs to enable it using `raspi-config`, which can be done in one line: ` if [[ $(raspi-config nonint get_legacy) == 1 ]]; then sudo raspi-config nonint do_legacy 0 && sudo sync && sudo reboot; fi `
- Any Raspberry Pi Camera will be constrained to work with a maximum resolution of 1920 x 1080 px, and/or with a maximum frame rate of 30 FPS.
- rpicam needs to be added into the GStreamer build to have the `rpicamsrc` plugin available.
> Add rpicamera support

- src/mavlink/mavlink_camera.rs
"Use MAV_AUTOPILOT_INVALID for components that are not flight
controllers." (https://mavlink.io/en/messages/common.html#HEARTBEAT)
Fixes #105.
> src: mavlink: Heartbeat should use MAV_AUTOPILOT_INVALID.

- Cargo.lock
- Cargo.toml
- regex 1.5.4 -> 1.6.0
- serde 1.0.133 -> 1.0.140
- serde_json 1.0.75 -> 1.0.82
- log 0.4.16 -> 0.4.17
- quick-xml 0.22.0 -> 0.23.0
- pnet 0.29.0 -> 0.31.0
- semver 1.0.7 -> 1.0.12
- mavlink 0.10.0 -> 0.10.1
- tokio 1.19 -> 1.20
- rand 0.8.4 -> 0.8.5
- reqwest 0.11.9 -> 0.11.11
- vergen 6.0.0 -> 7.3.1
> cargo: Upgrade several dependencies

- src/mavlink/mavlink_camera.rs
- src/stream/manager.rs
Closes #42
Closes #57 
Helps in both TCP and UDP cases, but none of these changes are necessary in order to make multiple cameras work. This PR is only improving the MAVLink (and therefore QGC) support.
> Add missing mavlink message

- src/stream/stream_backend.rs
Now that we are advertising via MAVLink with the same IP as the stream endpoint, we should allow the use of the local IP for RTSP (like `192.168.2.2`) instead of restricting it to `0.0.0.0`, so QGC can connect to it using the advertised IP, otherwise, QGC would be trying to connect to `0.0.0.0`, which will fail if the RTSP server and QGC are not both under the same localhost.
This solves the bug related to #114, but that issue should be kept open for further discussion over automatic IP.
> src: stream: Allow any IP for RTSP streams.

- src/settings/manager.rs
- src/stream/manager.rs
Only do that if the settings does not exist, or the user force the reset
> stream: manager: Do not crete streams if vector is empty

- Cargo.lock
- Cargo.toml
`enum-iterator` is a dependency for `vergen`, but because `v1.2.0` is causing
the `error[E0658]`, we are restricting its version by defining it as `~1.1.3`
here.
To give more context, until we've added tracing, vergen v1.1.3 had been chosen
by cargo. With tracing, if we use any version for vergen equal or greater than
v7.0.0, cargo jumps enum-iterator from v0.8.1 to v1.2.0, which will cause an
error when building in the CI:
```
error[E0658]: use of unstable library feature 'array_from_fn'
--> /root/.cargo/registry/src/github.com-1285ae84e5963aae/enum-iterator-1.2.0/src/lib.rs:554:18
|
554 |             Some(core::array::from_fn(|_| unreachable!()))
|                  ^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information
``` …
> Fix cargo build error[E0658]

- Cargo.lock
- Cargo.toml
The workaround is described in the previous commit: cef5990d3040f76a20a11282aaa97034b39af89e
> cargo: Upgrade vergen 7.4.1, remove enum-iterator workaround.

- src/mavlink/mavlink_camera.rs
From [mavlink camera protocol documentation](https://mavlink.io/en/services/camera.html), all MAV_CMD_XXX should have an ACK, but it was missing for `MAV_CMD_REQUEST_MESSAGE`.
To be clear, it isn't related to #57, but may help in future versions.
> src: mavlink: Fix missing ACK to MAV_CMD_REQUEST_MESSAGE.

- src/cli/manager.rs
- src/custom/bluerov.rs
- src/custom/mod.rs
- src/mavlink/mavlink_camera.rs
- src/network/utils.rs
This patch enhances our support for DHCP setups by:
1. Allowing the use of a Dynamic DNS, configured via CLI argument, to be used as the URI for the Mavlink camera XML file, as well in the RTSP stream URI, instead of directly using the local IP.
2. Allowing the creation of RTSP streams by default, opt-in via CLI argument.
---
Example:
> Create ROV RTSP default settings

- src/settings/manager.rs
Closes #81 by resetting the settings if incompatible, but before, it creates a simple copy as a backup.
> Fix settings

- src/stream/mod.rs
This acts as a workaround that (temporarily) closes #161, prioritizing the stability for an earlier release.
> src: stream:  Disable RTSP + UDP endpoints creation

- src/stream/manager.rs
- src/stream/pipeline/fake_pipeline.rs
- src/stream/pipeline/mod.rs
- src/stream/pipeline/redirect_pipeline.rs
- src/stream/pipeline/runner.rs
- src/stream/pipeline/v4l_pipeline.rs
- src/stream/sink/image_sink.rs
- src/stream/sink/mod.rs
- src/stream/sink/rtsp_sink.rs
- src/stream/sink/udp_sink.rs
- src/stream/sink/webrtc_sink.rs
- src/stream/webrtc/signalling_server.rs
Logging `self` is not useful and can freeze when the object has big arrays.
> src: stream: Add more log, skip unneeded information

- Cargo.lock
- Cargo.toml
- src/logger/manager.rs
Without integrate_spans() because it would significantly change the format of the GST logs we are already used to, also difficulting web search.
> cargo, src: Integrate GStreamer logs into Tracing

- src/cli/manager.rs
- src/logger/manager.rs
Although Tracy is super useful, it's only useful for development and it adds some overhead even when not being used, so I'll keep it disabled by default.
> Disable tracy by default

- src/stream/mod.rs
- src/stream/pipeline/runner.rs
Fixes #210 by connecting sinks before starting the pipeline.
Don't merge it yet as I'm still testing all cases.
Tests:
> Fix rtsp static rtsp sink

- src/stream/sink/udp_sink.rs
This reduces latency by sending packages as soon as the frames arrive, without waiting the theoretical FPS period.
Before: 192ms avg
After: 128ms avg
> Reduce UDP latency

- src/logger/manager.rs
unbelievable :facepalm: 
this span integration makes GStreamer more than double its CPU usage.
> src: logger: Only use gstreamer spam integration if necessary

- src/stream/sink/webrtc_sink.rs
Due to our need for low latency, there's no use case where we want to receive older packages via WebRTC.
> src: stream: sink: Disable retransmission for WebRTC

- src/stream/manager.rs
- src/stream/mod.rs
- src/stream/pipeline/fake_pipeline.rs
- src/stream/pipeline/mod.rs
- src/stream/pipeline/redirect_pipeline.rs
- src/stream/pipeline/runner.rs
- src/stream/pipeline/v4l_pipeline.rs
- src/stream/sink/image_sink.rs
- src/stream/sink/mod.rs
- src/stream/sink/rtsp_sink.rs
- src/stream/sink/udp_sink.rs
- src/stream/sink/webrtc_sink.rs
When a camera is disconnected during a stream, the system searches for the best device candidates that match the characteristics of the one in use on that stream, and recreates the stream from the ground up (while keeping the same pipeline ID). In the case of more than one stream running, the system discards any other device in the other stream.
To achieve that, the owner of the `<VideoAndStreamInformation>` was changed from the `<PipelineState>` (the inner state of each kind of `<Pipeline>`) to the `<Stream>`, while we moved part of the `<Stream>`'s fields to a thread-safe inner state called `<StreamState>`.
Closes #206
Closes #223
Closes #226
It's working, but it's a draft until I:
> Recreate streams

- src/stream/sink/image_sink.rs
This prevents panicking when the `discard-corrupted-frames` property is not available (old GStreamer)
> src: stream: image_sink: Only set property if it exists

- src/html/index.html
When mcm is running under nginx or something else, the redirects will not work if we use absolute paths.
> src: html: index: Avoid using absolute path for webrtc

- src/mavlink/manager.rs
It was 100Hz before the refactor, I mistakenly changed it to 100kHz, which causes the CPU usage to be high, around 30% higher in a Raspberry Pi 3.
> src: mavlink: Lower CPU usage by limmiting the send/recv loop max. frequency

- src/stream/manager.rs
- src/stream/sink/webrtc_sink.rs
- src/stream/webrtc/signalling_server.rs
- src/stream/webrtc/turn_server.rs
- src/stream/webrtc/webrtcbin_interface.rs
The thread leak was due to a reference to the webrtcbin element living inside the closures, keeping webrtcbin threads alive forever.
> Fix thread leak

- src/stream/webrtc/signalling_protocol.rs
This was preventing MCM from receiving ICE messages from the clients
> src: stream: webrtc: Fix wrong expected type for ufrag

- src/mavlink/mavlink_camera.rs
- src/stream/mod.rs
- src/stream/pipeline/runner.rs
The problem is that streams are recreated from inside the PipelineRunner context, which contrary to the main context, doesn't have a tokio runtime, thus, it panics when trying to spawn tokio tasks.
This is not the optimal solution 'cause every mavlink camera will end up creating a new tokio runtime, which is a waste of resources in this case, but still, this is a valid simple solution.
> Fix panic when recreating streams

- src/mavlink/manager.rs
> mavlink: Trigger reconnection from receiver_loop if any recv error happens

- Cargo.lock
- Cargo.toml
- src/cli/manager.rs
- src/helper/develop.rs
- src/helper/mod.rs
- src/helper/threads.rs
- src/main.rs
- src/server/manager.rs
- src/server/pages.rs
- src/stream/webrtc/frontend/src/App.vue
It's necessary to have chromedriver locally
> Add test to check webrtc task leak

- src/cli/manager.rs
The original logic fails to account for when the parameter was not passed because it has a default value.
> src: cli: Fix enable-webrtc-task-test always enabled

- Cargo.lock
- Cargo.toml
- src/cli/manager.rs
- src/custom/mod.rs
- src/logger/manager.rs
- src/main.rs
- src/mavlink/mavlink_camera.rs
- src/settings/manager.rs
Helps #321 
It appears that it did not fix the problem, this PR address the issue using the new configuration on clap 4.4 `default_missing_value`
> Update clap to 4.4

- README.md
libgstreamer1.0-x is required for pango, required for timeoverlay used on our fake streams
> readme: Add missing dependency

- src/main.rs
- src/mavlink/manager.rs
- src/mavlink/mavlink_camera.rs
- src/server/pages.rs
- src/settings/manager.rs
- src/stream/gst/utils.rs
- src/stream/manager.rs
- src/stream/mod.rs
- src/stream/pipeline/mod.rs
- src/stream/pipeline/runner.rs
- src/stream/sink/image_sink.rs
- src/stream/sink/rtsp_sink.rs
- src/stream/sink/udp_sink.rs
- src/stream/sink/webrtc_sink.rs
note: **Merge after #303**
This work:
- Fix critical crashes when recreating streams
- Fix MAVlink-related thread leak that leads to a crash or complete stall caused by thread starvation
- Helps #310 because it fixes a thread leak related to the Mavlink and stream recreation
- May helps #308
> Fix stream recreation crashes and thread starvation caused by MAVLink-related thread leak

- src/stream/pipeline/fake_pipeline.rs
- src/stream/pipeline/mod.rs
- src/stream/pipeline/redirect_pipeline.rs
- src/stream/pipeline/v4l_pipeline.rs
- src/stream/sink/image_sink.rs
This patch removes the need for some sinks (ImageSink for now, WebRTCSink in the future) to have to un an RTP depayloader and/or video parser.
It does so by adding a second Tee just before the payloader.
The older Tee, previously called "SinkTee", is now named "RTPTee", while the newer is called "VideoTee".
Relates to #274.
> Add video tee

- src/cli/manager.rs
- src/mavlink/mavlink_camera_component.rs
> Allow MAVLink System ID to be specified via CLI argument

- src/stream/pipeline/v4l_pipeline.rs
- src/stream/sink/webrtc_sink.rs
This patch:
* Fixes the frame duration, which fixes the FPS reported from different applications when a video is recorded from our WebRTC.
* might help [this Cockpit issue](https://github.com/bluerobotics/cockpit/issues/794).
> src: stream: pipeline: Fix wrong frame duration

- src/stream/rtsp/rtsp_server.rs
Fixes #354 
This is partially a revert of #332
> src: stream: rtsp: shmsrc needs to do-timestamp

- src/mavlink/manager.rs
Finally, the clogging is solved.
lesson learned: Do not sleep on network-receiving, or channel-receiving loops.
The CPU usage on RPI4 spikes +6% when exchanging information back and forth with the GCS.
Closes #354
> Fix mavlink unresponsiveness / lateness.

- src/stream/manager.rs
- src/stream/mod.rs
Closes #360
The problem was that RTSP was not finished before we tried to recreate it, so the server skipped the new one.
To drop the current StreamState before having a new one, we wrapped it around an Option, allowing us to take and drop it instead of dropping it when dereferencing and overwriting it.
> src: stream: Completely drop the stream before creating a new one

- README.md
> readme: Add information of availability of WebRTC

- .github/workflows/test_webrtc_leak.yml
- src/custom/mod.rs
- src/custom/test.rs
- src/helper/develop.rs
The test runs fine locally with:
```
cargo run --verbose -- --mavlink udpin:0.0.0.0:6666 --verbose --enable-thread-counter --enable-webrtc-task-test --default-settings WebRTCTest --reset
```
No idea why is failing on CI, crashing in a wrong scenario. I believe that @joaoantoniocardoso async rework may fix the issue on CI for this patch.
> Add webrtc test via CI

- src/stream/sink/webrtc_sink.rs
- src/stream/webrtc/signalling_server.rs
> Add failsafe killer

- src/stream/rtsp/rtsp_server.rs
TCP is the default for RTSP, for current format, the user should use rtspu
> stream: rtsp: Add TCP back in RTSP

- src/stream/mod.rs
- src/stream/pipeline/mod.rs
- src/stream/rtsp/mod.rs
- src/stream/rtsp/rtsp_scheme.rs
- src/stream/rtsp/rtsp_server.rs
- src/stream/sink/rtsp_sink.rs
Tested and working with both `rtspsrc` and ffplay:
Note: a drawback of this approach is that despite the scheme used in the endpoint, the RTSP client would always use `rtsp://` instead.
> Add rtsp protocol options via schemes

- src/stream/gst/utils.rs
- src/stream/pipeline/fake_pipeline.rs
- src/stream/pipeline/mod.rs
- src/stream/pipeline/qr_pipeline.rs
- src/stream/sink/image_sink.rs
- src/video/types.rs
- src/video/video_source_gst.rs
To receive RGB:
```
gst-launch-1.0 -v udpsrc address=0.0.0.0 port=5602 close-socket=false auto-multicast=true \
caps="application/x-rtp, sampling=(string)RGB, width=(string)320, height=(string)320, payload=(int)96" \
! rtpvrawdepay ! videoconvert ! fpsdisplaysink sync=false
```
To Receive H264:
```
gst-launch-1.0 udpsrc port=5602 caps='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264' ! rtph264depay ! avdec_h264 ! clockoverlay valignment=bottom ! autovideosink sync=true
```
> Add support to QrTimeStamp plugin

- src/lib/stream/rtsp/rtsp_server.rs
- src/lib/stream/sink/rtsp_sink.rs
The `is-live=true` in `shmsrc` was adding ~1 frame of latency, while the `sync=true` in `shmsink` was adding more ~2.
tested:
How to test:
1. Create a QrTimestamp 320x320@30fps RTSP stream as below:
2. To receive it, run the following line:
```
clear; GST_DEBUG="*:3,*qrtimestampsink*:5" gst-launch-1.0 -v \
rtspsrc location=rtsp://192.168.100.2:8554/test is-live=true latency=0 \
! application/x-rtp,payload=96 \
! rtph264depay \
! h264parse \
! avdec_h264 discard-corrupted-frames=true \
! videoconvert \
! qrtimestampsink
```
Before this patch (master), the expected latency is ~100 ms. 
After this patch it is ~34 ms (which is the same as the UDP)
> src: lib: stream: Improve RTSP latency

- src/lib/stream/sink/rtsp_sink.rs
This helps with stability when creating raw RTSP streams.
- tested both locally (Linux) and on BlueOS
> src: lib: stream: sink: shmsink doesn't need to wait

- src/lib/stream/sink/webrtc_sink.rs
Supposedly this is all we need to make the retransmission work with the [RFC4588](https://datatracker.ietf.org/doc/html/rfc4588).
I checked the resulting SDP, and it has all it needs:
Sender (this branch):
```rust
v=0
o=- 2461340508447355243 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0
m=video 9 UDP/TLS/RTP/SAVPF 96 97
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:Imt2ypYqN8nzjQx6HzC6smEMvF+OvhaA
a=ice-pwd:MYE+ApE38JDaDQgwKN7B3LvJ53RA4BcH
a=rtcp-mux
a=rtcp-rsize
a=sendonly
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 transport-cc
a=framerate:30
a=rtpmap:97 rtx/90000
a=ssrc-group:FID 3729522813 1429131839
a=ssrc:3729522813 msid:user3977049223@host-7363340d webrtctransceiver0
a=ssrc:3729522813 …
```
> src: libn: stream: sink: Enable Nack

- src/lib/controls/onvif/manager.rs
- src/lib/logger/manager.rs
- src/lib/mavlink/manager.rs
To see again those messages:
```
export RUST_LOG=debug,mavlink_camera_manager::controls::onvif=trace,mavlink_camera_manager::mavlink=trace
```
note: a more fine-grained control is also possible if needed
Closes #443
Closes #51
> Fix verbosity

- src/lib/mavlink/mavlink_camera.rs
- src/lib/stream/mod.rs
- src/lib/stream/pipeline/fake_pipeline.rs
- src/lib/stream/pipeline/v4l_pipeline.rs
- src/lib/stream/rtsp/rtsp_server.rs
- src/lib/stream/sink/image_sink.rs
- src/lib/stream/sink/udp_sink.rs
- src/lib/stream/sink/webrtc_sink.rs
- src/lib/video/local/video_source_local_linux.rs
- src/lib/video/types.rs
- src/lib/video/video_source_gst.rs
What to test:
¹: It works on Safari 18, but for 17.6, the H265 feature flag needs to be enabled.
---
To receive from UDP:
```bash
gst-launch-1.0 -vc \
udpsrc address=127.0.0.1 port=5600 close-socket=false auto-multicast=true \
! application/x-rtp, payload=96 \
! rtph265depay \
! avdec_h265 std-compliance=normal \
! videoconvert \
! autovideosink sync=false
```
To receive from RTSP:
```bash
gst-launch-1.0 -vc \
rtspsrc location=rtsp://0.0.0.0:8554/0 latency=0 \
! application/x-rtp, payload=96 \
! rtph265depay \
! avdec_h265 std-compliance=normal \
! videoconvert \
! autovideosink sync=false
```
---
Useful to check if the system supports H265 decoding (which doesn't mean it supports it via WebRTC): 
1. open [video_demo_hevc](https://lf-tk-sg.ibytedtos.com/obj/tcs-client-sg/resources/video_de …
> Add H265 support - Part I: Fake + V4L2

- src/lib/controls/onvif/camera.rs
- src/lib/controls/onvif/manager.rs
- src/lib/controls/onvif/mod.rs
- src/lib/custom/bluerov.rs
- src/lib/custom/mod.rs
- src/lib/logger/manager.rs
- src/lib/mavlink/mavlink_camera.rs
- src/lib/server/pages.rs
- src/lib/settings/manager.rs
- src/lib/stream/gst/utils.rs
- src/lib/stream/manager.rs
- src/lib/stream/mod.rs
- src/lib/stream/pipeline/mod.rs
- src/lib/stream/pipeline/onvif_pipeline.rs
- src/lib/stream/pipeline/runner.rs
- src/lib/stream/sink/webrtc_sink.rs
- src/lib/stream/webrtc/signalling_server.rs
- src/lib/video/local/video_source_local_linux.rs
- src/lib/video/local/video_source_local_none.rs
- src/lib/video/mod.rs
- src/lib/video/types.rs
- src/lib/video/video_source.rs
- src/lib/video/video_source_gst.rs
- src/lib/video/video_source_onvif.rs
- src/lib/video/video_source_redirect.rs
- src/lib/video/xml.rs
- src/main.rs
With this patch, Onvif is now a Video Source, and also a Pipeline, allowing the same API and workflow as for v4l cameras, which means we have all sinks support: UDP/RTSP/Thumbnail/WebRTC.
> Add h265 support - Part II: Onvif

- src/lib/stream/gst/utils.rs
5s is not enough for all RTSP servers.
> src: lib: stream: gst: utils: Increase timout for encode discovery

- Cargo.toml
- src/lib/cli/manager.rs
- src/lib/controls/onvif/camera.rs
- src/lib/controls/onvif/manager.rs
- src/lib/logger/manager.rs
- src/lib/server/manager.rs
- src/lib/server/pages.rs
- src/lib/video/video_source_onvif.rs
- Closes #451 
- Closes #452
To be done next:
- Add UI
- Store credentials in the settings
> Onvif auth

- Cargo.lock
- Cargo.toml
- src/lib/server/error.rs
- src/lib/server/mod.rs
- src/lib/server/pages.rs
This way it produces a 100% valid docs.json
> Fix openapi

- src/lib/controls/onvif/camera.rs
- src/lib/stream/gst/utils.rs
- src/lib/stream/mod.rs
- src/lib/stream/pipeline/redirect_pipeline.rs
Since WebRTC only works with a narrow option of stream formats, we are now re-encoding the RTP packages for Redirect streams, using the same strategy as for the Onvif sources.
An example is the stream from the Swell Pro. It's a 720p H264 stream but with an RTP incompatible with WebRTC.
> Improve Redirect to WebRTC compatibility

- src/lib/server/manager.rs
- src/lib/server/pages.rs
Scenario:
I'm using "Redirect" option in stream configuration, and if the source is not available during mavlink-camera-manager initialization, then signalling server and WebRTC won't be able to serve this stream when it becomes available
The config I use:
```
{
"header": {
"name": "Camera Manager",
"version": 0
},
"mavlink_endpoint": "udpin:0.0.0.0:14550",
"streams": [
{
"name": "Some RTSP stream",
"stream_information": {
"endpoints": [
"rtsp://127.0.0.1:8889/stream"
],
"configuration": {
"type": "video",
"encode": "H264",
"height": 0,
"width": 0,
"frame_interval": {
"numerator": 0,
"denominator": 0
}
},
"extended_configuration": {
"thermal": false,
"disable_mavlink": true
}
},
"video_source": {
"Redirect": {
"name": "Some RTSP stream",
"source": {
"Redirect": "Redirect"
}
}
}
}
]
}
``` …
> Ability to restart streams with REST API

- src/lib/stream/manager.rs
Once I added the restart_streams API I found that manager::start_default function has the next line
```
// Gently remove all streams as we are going to replace the entire list below
remove_all_streams().await?;
```
Which was removing the full configuration. After a restart, the config contains the streams that were available during the restart and other disappeared
`remove_all_streams` is only called from `start_default`, so I decided to resolve this simply by providing a flag, that allow or prevent the config file from modification
What do you think?
> feature: keep config persistent after reset or restart if the stream is unavailable during restart

- src/lib/mavlink/mavlink_camera_component.rs
- src/lib/stream/gst/utils.rs
- src/lib/stream/manager.rs
- src/lib/stream/mod.rs
- src/lib/stream/pipeline/fake_pipeline.rs
- src/lib/stream/pipeline/mod.rs
- src/lib/stream/pipeline/onvif_pipeline.rs
- src/lib/stream/pipeline/qr_pipeline.rs
- src/lib/stream/pipeline/redirect_pipeline.rs
- src/lib/stream/pipeline/runner.rs
- src/lib/stream/pipeline/v4l_pipeline.rs
- src/lib/stream/sink/image_sink.rs
- src/lib/stream/sink/mod.rs
- src/lib/stream/sink/rtsp_sink.rs
- src/lib/stream/sink/udp_sink.rs
- src/lib/stream/sink/webrtc_sink.rs
- src/lib/stream/types.rs
- src/lib/stream/webrtc/signalling_server.rs
- Closes #466 
- Closes #345
By adding a stream, the system first adds it to the manager, and then the watcher task keeps trying to actually create the stream.
The downside is that the user won't have an immediate error returning from the stream creation, and he would have to check the `running` state. To address this, an optional "error" field was added to the StreamStatus so the user can have feedback on what is going on inside the stream creation.
> Rework streams creation

- src/lib/stream/gst/utils.rs
- src/lib/stream/mod.rs
- src/lib/video/local/video_source_local_linux.rs
Every time some client requests the available streams, MCM throws all these logs:
Since RadCam Manager is a client that requests that every second, the size of the logs is getting huge.
This PR addresses that by making those logs only available via trace.
> src: lib: video: local: Reduce V4L verbosity

- src/lib/stream/sink/image_sink.rs
- src/lib/stream/sink/udp_sink.rs
Oops, I missed this part: we need to set the state to Null of any pipeline created by the sink, otherwise, that pipeline lives forever.
> src: lib: stream: sink: Add missing set_state to UDP and Image sinks

- .github/workflows/deploy.yml
1.22.7 (the default used by the action) is no longer available, so we are moving to the latest stable release.
> .github: Update GST version for windows/macos

- src/lib/controls/onvif/manager.rs
This fixes the loss of track of streams from devices after being authenticated
Closes #488
> Use unauthenticated URIs for streams information

- src/lib/stream/sink/image_sink.rs
blocking inside GStreamer task is not the best idea
> src: lib: stream: sink: image_sink: Remove delay to avoid contention inside gstreamer stream thread

- src/html/index.html
- src/lib/stream/mod.rs
- src/lib/stream/types.rs
This patch allows users to disable thumbnails (image sink) or zenoh (zenih sink) when creating each stream. The default behavior is both enable.
Closes #518
> Allow disabling thumbnails and zenoh
