mavlink/mavlink-camera-manager

Cargo.lock
Cargo.toml

Cargo: update paperclip

---

Cargo.lock
Cargo.toml
src/stream/gst/pipeline_runner.rs
src/stream/video_stream_udp.rs

- glib 0.10.2 -> 0.14.8
- gstreamer 0.16.3 -> 0.17.4
- gstreamer-rtsp-server 0.16.3 -> 0.17.2

Upgrade glib, gstreamer, gstreamer-rtsp-server

---

.github/workflows/rust.yml
src/mavlink/mavlink_camera.rs

mavlink_camera: Add port for url on camera_information

---

README.md

README: Update action badge

---

src/mavlink/mavlink_camera.rs
src/stream/manager.rs

Fixes https://github.com/bluerobotics/mavlink-camera-manager/issues/38.

src: video,stream: Set mavtype according to the video stream type

---

src/mavlink/mavlink_camera.rs

The IP should be visible for outside services, 0.0.0.0 will not work

mavlink: mavlink_camera: Replace localhost address with public ip

---

src/custom/bluerov.rs
src/html/index.html
src/mavlink/mavlink_camera.rs
src/settings/manager.rs
src/stream/manager.rs
src/stream/stream_backend.rs
src/stream/types.rs
src/video/types.rs

Add thermal camera flag

---

src/server/manager.rs

src: server: Fix Swagger Info.

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
src/html/webrtc/index.html
src/html/webrtc/webrtc.js
src/server/manager.rs
src/server/pages.rs
src/stream/gst/pipeline_runner.rs
src/stream/manager.rs
src/stream/mod.rs
src/stream/signalling_server.rs
src/stream/stream_backend.rs
src/stream/turn_server.rs
src/stream/types.rs
src/stream/video_stream_redirect.rs
src/stream/video_stream_rtsp.rs
src/stream/video_stream_udp.rs
src/stream/video_stream_webrtc.rs

Add webrtc

---

src/mavlink/mavlink_camera.rs

This adds the basic ability to have camera controls set by QGC.

Fix PARAM_EXT_SET

---

src/html/index.html
src/mavlink/mavlink_camera.rs
src/server/manager.rs
src/server/pages.rs
src/video/video_source.rs

Add reset camera controls (mavlink and API)

---

src/logger/manager.rs

src: logger: Use RUST_LOG over variable to control verbosity

---

src/html/index.html

Add dark theme for testing webpage

---

src/server/pages.rs

Remove an unused parameter left after #89's rebase on top of commit 876b266ced7315e9ee9e723a98347acb3070c464

src: server: Remove unused parameter.

---

Cargo.lock
Cargo.toml
src/video/video_source_local.rs

cargo, src: video: Upgrade to v4l 0.13.0

---

src/network/utils.rs

src: network: Use the ip from default interface.

---

Cargo.lock
Cargo.toml
src/video/video_source_local.rs

Reverts bluerobotics/mavlink-camera-manager#102 because of #96 .

Revert "cargo, src: video: Upgrade to v4l 0.13.0"

---

src/mavlink/mavlink_camera.rs

src: mavlink: Try to reconnect if lost connection.

---

src/html/index.html
src/mavlink/mavlink_camera.rs
src/stream/gst/pipeline_builder.rs
src/stream/manager.rs
src/stream/rtsp_server.rs
src/stream/stream_backend.rs
src/video/video_source_local.rs
src/video_stream/types.rs

This has been annoying me for ages.

Small refactor for better errors

---

src/mavlink/mavlink_camera.rs

Log when Id is not found when Dropping MavlinkCameraComponent

---

src/cli/manager.rs
src/stream/gst/utils.rs
src/stream/manager.rs
src/stream/mod.rs

This PR closes #118 by using the following (for example) command line in Raspberry Pi:
```bash
mavlink-camera-manager \
--default-settings BlueROVUDP \
--mavlink udpout:127.0.0.1:14001 \
--verbose \
--gst-feature-rank omxh264enc=0,v4l2h264enc=250,x264enc=260
```
---

Fix webrtc

---

.github/workflows/linux-arm-rtsp.yml

Ref: https://github.com/actions/runner-images/issues/6002
Fix arm CI

github: linux-arm-rtsp: Move away from deprecated ubuntu version

---

src/settings/manager.rs

Fix no mavlink_endpoint in settings after reset

---

src/stream/stream_backend.rs

I was studying when I saw this simple solution.
Solves #35

src: stream: Ensure StreamBackend also have Drop implemention.

---

src/stream/pipeline/pipeline.rs

stream: pipeline: pipeline: Add inner_state function

---

src/stream/stream.rs

stream: stream: Use 'matches!' over if let pattern

---

src/stream/pipeline/v4l_pipeline.rs
src/video/video_source_local.rs

Because the raspberry camera's driver is (very) susceptible to fail under unsupported parameters, causing kernel Oopsies, we can't test profiles and let the resolution and interval unset. Instead, we need to provide one of the constrained combinations of resolution and intervals that we know will not cause the driver to fail. Even beyond this already worked-around limitation, it seems its driver can fail if we set an unsupported profile as well. That being said, now, instead of testing our known profiles, we let GStreamer choose its preferred, and we stick with it.

Fix v4l profile discovery

---

src/stream/pipeline/fake_pipeline.rs
src/stream/pipeline/pipeline.rs
src/stream/pipeline/v4l_pipeline.rs
src/stream/rtsp/rtsp_server.rs
src/stream/sink/rtsp_sink.rs

I'll rebase to master after #155

Add raw and jpeg

---

Cargo.lock
Cargo.toml
src/stream/manager.rs
src/video/video_source_local.rs

src: stream, video: Fix and improve device identification

---

src/server/manager.rs
src/server/pages.rs
src/stream/manager.rs
src/stream/sink/rtsp_sink.rs
src/stream/sink/sink.rs
src/stream/sink/udp_sink.rs
src/stream/sink/webrtc_sink.rs

* UDP - works with VLC and GStreamer for H264, RAW, and MJPG.
* RTPS - both VLC and GStreamer parse it, but they refuse to play it.
closes #17

src: sink: Implement SDP generation for sink interface

---

src/stream/gst/utils.rs
src/stream/manager.rs
src/stream/pipeline/mod.rs
src/stream/pipeline/runner.rs
src/stream/pipeline/v4l_pipeline.rs

The supposed thread leaks happening when failing to create streams were due to this never returning condition.
* Helps #79
* Closes #163
* Closes #170

Fix non returning api requests and supposedly thread leaks

---

src/stream/webrtc/signalling_server.rs

src: stream: Filter out non-H264 local streams for WebRTC

---

Cargo.lock
Cargo.toml
src/server/manager.rs
src/server/pages.rs
src/stream/manager.rs
src/stream/mod.rs
src/stream/pipeline/fake_pipeline.rs
src/stream/pipeline/mod.rs
src/stream/pipeline/redirect_pipeline.rs
src/stream/pipeline/v4l_pipeline.rs
src/stream/sink/image_sink.rs
src/stream/sink/mod.rs
src/stream/sink/rtsp_sink.rs
src/stream/sink/udp_sink.rs
src/stream/sink/webrtc_sink.rs

Closes #143
Fixes #161 (the underlying problem, although RTSP + UDP is kept disabled)

Add thumbnailer

---

src/stream/webrtc/signalling_server.rs

src: stream: Prevent panic from signalling server

---

Cargo.lock
Cargo.toml
src/server/manager.rs
src/server/pages.rs
src/stream/manager.rs
src/stream/sink/image_sink.rs

To be rebased, reviewed, and merged after #203 
Closes #179

Fix thumbnail

---

src/stream/manager.rs

src: stream: Nicely remove all streams before create the defaults

---

src/stream/manager.rs

src: stream: Fix default streams not starting up after a single reset

---

Cargo.lock
Cargo.toml
src/stream/sink/webrtc_sink.rs

Fix webrtc sdp

---

src/stream/pipeline/mod.rs
src/stream/pipeline/runner.rs
src/stream/sink/image_sink.rs
src/stream/sink/udp_sink.rs

This way we have more useful dot files

src: stream: Move most dot files to inside pipeline runner

---

src/stream/pipeline/mod.rs

Closes #229 
This is a workaround as it's better to keep consuming resources than have to restart the whole stream just because the client closed the stream.

src: stream: pipeline: Don't pause redirect's rtspsrc.

---

src/mavlink/mavlink_camera.rs

For every Clone, a Drop can happen, and in this case, we want Drop to be called only once.
Fixes #238

src: mavlink: Avoid Clone to avoid unwanted Drops

---

src/stream/pipeline/runner.rs

ref: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1659

src: stream: pipeline: Treat Latency messages

---

src/stream/pipeline/mod.rs
src/stream/rtsp/rtsp_server.rs

Fix RTSP streams recreation

---

README.md

readme: Add Node/Yarn step with instructions

---

src/custom/bluerov.rs
src/server/pages.rs
src/stream/manager.rs
src/stream/rtsp/rtsp_server.rs
src/stream/sink/image_sink.rs
src/stream/sink/rtsp_sink.rs
src/stream/sink/udp_sink.rs
src/stream/sink/webrtc_sink.rs
src/video/video_source_local.rs

src: Update to rustfmt 1.6.0-stable (5680fa1 2023-08-23) new standards

---

src/mavlink/manager.rs

src: mavlink: Use RWLock when possible

---

src/settings/manager.rs

Fix #251
Fix #272
Not the best approach, but it fixes.

Fix settings on first use

---

src/stream/sink/rtsp_sink.rs

This is also needed to fix #354 depending on the GStreamer version.

src: stream: rtsp: shmsrc needs to wait for connection

---

src/mavlink/mavlink_camera.rs

The problem is that the added delay was causing the subscription to be always late.
Closes #354

grc: mavlink: Fix mavlink camera compoenent never answering QGC

---

src/video/video_source_local.rs

Fix v4l panics

---

src/stream/webrtc/signalling_server.rs

Now a single websocket can be used to any number of webrtc clients

src: stream: webrtc: Fix Signalling server websocket and mpsc management

---

src/stream/webrtc/frontend/package.json
src/stream/webrtc/frontend/src/App.vue
src/stream/webrtc/frontend/src/consumer.ts
src/stream/webrtc/frontend/src/manager.ts
src/stream/webrtc/frontend/src/session.ts
src/stream/webrtc/frontend/src/signaller.ts
src/stream/webrtc/frontend/yarn.lock

This patch adds some useful controls to test/compare streams

Improve webrtc5

---

.github/workflows/test_webrtc_leak.yml
README.md
src/custom/test.rs
src/helper/develop.rs
src/helper/threads.rs

Make it more replicable and easier to understand

Improve webrtc test

---

.github/workflows/deploy-unix.yml
.github/workflows/rust.yml

- moves out from action-rs as they got archived.
- reduces ~2min by caching apt

.github: Update workflows

---

src/logger/manager.rs

This formatting follows the original default GStreamer format, and has little overhead. Example of output:
```rust
2024-05-30T21:35:37.556164Z  INFO                 main ThreadId(01) src/logger/manager.rs:110: GST_PIPELINE ../gstreamer/subprojects/gstreamer/gst/gstparse.c:344:gst_parse_launch_full parsing pipeline description 'rtspsrc location=rtsp://127.0.0.1:8554/test is-live=true latency=0 ! application/x-rtp ! tee name=RTPTee-ecf8c718-760c-4f78-adbf-78478d7a02f8 allow-not-linked=true'
2024-05-30T21:35:37.556565Z  INFO                 main ThreadId(01) src/logger/manager.rs:110: GST_PLUGIN_LOADING ../gstreamer/subprojects/gstreamer/gst/gstplugin.c:995:_priv_gst_plugin_load_file_for_registry plugin "/usr/lib/gstreamer-1.0/libgstrtsp.so" loaded
2024-05-30T21:35:37.557034Z  INFO …
```

src: logger: Fix gstreamer log integration

---

Cargo.toml

Cargo: Move v4l to unix target

---

Cargo.lock
Cargo.toml
src/server/manager.rs

Allow all CORS

---

src/video/xml.rs

Example:
```xml
<mavlinkcamera>
<definition version="1">
<model>H264 USB Camera: USB Camera</model>
<vendor>Missing</vendor>
</definition>
<parameters>
<parameter name="9963776" type="int64" default="0" v4l_id="9963776" step="1" max="64" min="-64">
<description>Brightness</description>
</parameter>
<parameter name="9963777" type="int64" default="32" v4l_id="9963777" step="1" max="64" min="0">
<description>Contrast</description>
</parameter>
<parameter name="9963778" type="int64" default="56" v4l_id="9963778" step="1" max="128" min="0">
<description>Saturation</description>
</parameter>
<parameter name="9963779" type="int64" default="0" v4l_id="9963779" step="1" max="40" min="-40">
<description>Hue</description>
</parameter>
<parameter name="9963788" type="bool" default="1" …
```

src: video: xml: Flatten is working

---

Cargo.lock
Cargo.toml
src/cli/manager.rs

Fix path expansion

---

src/lib/cli/manager.rs
src/lib/stream/sink/webrtc_sink.rs

Closes https://github.com/mavlink/mavlink-camera-manager/issues/184

Add turn servers config via cli

---

src/lib/stream/webrtc/frontend/tsconfig.json

We only need to check our own code, not our dependencies

src: stream: frontend: tsconfig: Skip libraries check

---

.github/workflows/deploy.yml
.github/workflows/rust.yml
.github/workflows/test_webrtc_leak.yml
.gitmodules
Cargo.lock
Cargo.toml
src/lib/controls/mod.rs
src/lib/controls/onvif/client.rs
src/lib/controls/onvif/manager.rs
src/lib/controls/onvif/mod.rs
src/lib/controls/types.rs
src/lib/logger/manager.rs
src/lib/mavlink/utils.rs
src/lib/mod.rs
src/lib/server/pages.rs
src/lib/stream/types.rs
src/lib/video/local/video_source_local_linux.rs
src/lib/video/local/video_source_local_none.rs
src/lib/video/types.rs
src/lib/video/video_source.rs
src/lib/video/video_source_gst.rs
src/lib/video/video_source_redirect.rs
src/lib/video/xml.rs
src/main.rs

Find and register available streams

Onvif: Add first support

---

src/lib/stream/sink/webrtc_sink.rs

src: lib: stream: sink: Set RTP Storage to 1 second

---

src/lib/mavlink/manager.rs

src: lib: mavlink: Respect new camera IDs range

---

src/lib/stream/gst/utils.rs
src/lib/stream/mod.rs

Improve capture configuration discovery

---

src/lib/stream/manager.rs

Helps #464
Continuation of #468

src: lib: stream: Fix access to video_and_stream_information for stateless streams

---

README.md

As a feedback from the community, someone was trying to run it on Windows using an older MSVC version, so I'm adding installation instructions here for both Windows and macOS.
note: I haven't tested neither of them by myself

readme: Improve installation instructions

---

src/lib/cli/manager.rs
src/lib/mavlink/manager.rs
src/lib/mavlink/mavlink_camera.rs
src/lib/stream/mod.rs

Allow configurable cameras IDs

---

Cargo.lock
Cargo.toml
src/lib/stream/manager.rs
src/lib/stream/mod.rs
src/lib/stream/webrtc/signalling_server.rs

Fix stream UUID

---

src/lib/controls/onvif/manager.rs
src/lib/server/pages.rs

Reset onvif when requested

---

src/lib/stream/pipeline/fake_pipeline.rs

Closes #492
reference: [1](https://gstreamer.freedesktop.org/documentation/mediafoundation/mfh264enc.html?gi-language=c#mfh264enc) [2](https://gstreamer.freedesktop.org/documentation/mediafoundation/mfh265enc.html?gi-language=c#mfh265enc)

src: lib: stream: pipeline: Fix fakesrc on Windows

---

src/lib/controls/onvif/manager.rs

:tada: 
Onvif discovery task was silently returning on run() failure, which happens whenever the system has no multicast access.
Closes #498

src: lib: controls: onvif: Don't end task on discovery run failure

---

src/html/index.html
src/lib/server/manager.rs
src/lib/server/pages.rs
src/lib/stream/manager.rs
src/lib/stream/mod.rs
src/lib/stream/sink/image_sink.rs
src/lib/stream/sink/mod.rs
src/lib/stream/sink/rtsp_sink.rs
src/lib/stream/sink/udp_sink.rs
src/lib/stream/sink/webrtc_sink.rs

I would prefer to use egui on the front, but oh well... html it's

Render dot streams in the frontend

---

src/lib/custom/bluerov.rs

src: lib: custom: Use only even port numbers for video sources

---

src/lib/stream/mod.rs

src: lib: stream: Use video source name instead of stream name to generate pipeline ID

---

Cargo.lock
Cargo.toml
src/lib/stream/sink/rtsp_sink.rs

Fix shmsink failure rtsp

---

src/lib/mavlink/mavlink_camera.rs
src/lib/mavlink/mavlink_camera_component.rs
src/lib/stream/gst/utils.rs
src/lib/stream/manager.rs
src/lib/stream/mod.rs
src/lib/stream/pipeline/fake_pipeline.rs
src/lib/stream/pipeline/mod.rs
src/lib/stream/pipeline/onvif_pipeline.rs
src/lib/stream/pipeline/qr_pipeline.rs
src/lib/stream/pipeline/redirect_pipeline.rs
src/lib/stream/pipeline/runner.rs
src/lib/stream/pipeline/v4l_pipeline.rs
src/lib/stream/sink/image_sink.rs
src/lib/stream/sink/mod.rs
src/lib/stream/sink/rtsp_sink.rs
src/lib/stream/sink/udp_sink.rs
src/lib/stream/sink/zenoh_sink.rs
src/lib/stream/webrtc/signalling_server.rs
src/lib/stream/webrtc/turn_server.rs

No more repeated fields in the logs:
```
2025-09-27T13:16:23.945749Z DEBUG watcher{video_and_stream_information=RwLock { data: VideoAndStreamInformation { name: "ball - Fake source", stream_information: StreamInformation { endpoints: [Url { scheme: "udp", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("0.0.0.0")), port: Some(5600), path: "", query: None, fragment: None }], configuration: Video(VideoCaptureConfiguration { encode: H264, height: 1080, width: 1920, frame_interval: FrameInterval { numerator: 1, denominator: 30 } }), extended_configuration: Some(ExtendedConfiguration { thermal: false, disable_mavlink: true }) }, video_source: Gst(VideoSourceGst { name: "Fake source", source: Fake("ball") }) } } pipeline_id=b4e7d147-249b-506d-974c-e8b0c7624be3 …
```

Improve logs2

---

src/lib/stream/gst/utils.rs
src/lib/stream/pipeline/onvif_pipeline.rs
src/lib/stream/pipeline/redirect_pipeline.rs

This improves our success rate, as sometimes it was choosing the audio channel :disappointed:

src: lib: stream: gst: utils: Filter out non-video channels in rtspsrc
